azs:
- name: z1
- name: z2
- name: z3

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    memory: 4096
    ephemeral_disk: 10240
# Required by postgres-release, cf-deployment
- name: small
  cloud_properties:
    cpu: 1
    memory: 2048
    ephemeral_disk: 10240
# Used by cf-deployment
- name: minimal
  cloud_properties:
    cpu: 2
    memory: 1024
    ephemeral_disk: 10240
- name: small-highmem
  cloud_properties:
    cpu: 2
    memory: 4096
    ephemeral_disk: 10240

disk_types:
- name: default
  disk_size: 1024
# Required by postgres-release, cf-deployment
- name: 10GB
  disk_size: 10240
# Used by cf-deployment
- disk_size: 5120
  name: 5GB
- disk_size: 100240
  name: 100GB

networks:
- name: default
  type: manual
  subnets:
  - azs: [z1,z2,z3]
    range: 192.168.123.0/24
    dns: [192.168.5.1]
    reserved: 192.168.123.2-192.168.123.10
    gateway: 192.168.123.1
    static: 192.168.123.250-192.168.123.254

vm_extensions:
- name: 50GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk: 51_200
- name: 100GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk: 102_400
- name: diego-ssh-proxy-network-properties
- name: cf-router-network-properties
- name: cf-tcp-router-network-properties

compilation:
  workers: 5
  az: z1
  reuse_compilation_vms: true
  vm_type: default
  network: default
