azs:
- name: z1
- name: z2
- name: z3

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    memory: 4096
    ephemeral_disk: 16384
# Required by postgres-release, cf-deployment
- name: small
  cloud_properties:
    cpu: 1
    memory: 2048
    ephemeral_disk: 2048

disk_types:
- name: default
  disk_size: 1024
# Required by postgres-release, cf-deployment
- name: 10GB
  disk_size: 10240

networks:
- name: default
  type: manual
  subnets:
  - azs: [z1,z2,z3]
    range: 192.168.123.0/24
    dns: [8.8.8.8]
    reserved: 192.168.123.2-192.168.123.10
    gateway: 192.168.123.1
    static: 192.168.123.250-192.168.123.254

#vm_extensions:

compilation:
  workers: 1
  az: z1
  reuse_compilation_vms: true
  vm_type: default
  network: default
