deployment_name: concourse
network_name: default
web_vm_type: default
db_persistent_disk_type: default
db_vm_type: default
worker_vm_type: default
web_ip: 192.168.123.250
external_url: http://192.168.123.250
local_user:
  username: admin
  password: admin
