# Rendered with Go text templates, see https://golang.org/pkg/text/template/
- type: replace
  path: /resource_pools/name=vms/cloud_properties/libvirt?
  value:
    storage_pool_name: ((libvirt_storage_pool_name))
    network_name: ((libvirt_network_name))
    network_dhcp_ip: |
      <host name='{{.VmName}}' ip='{{.IpAddress}}'/>
    boot_device: |
      <disk type='file' device='disk'>
        <driver name='qemu' type='qcow2' cache='none'/>
        <source file='{{.TargetPath}}'/>
        <target dev='{{.TargetDevice}}'/>
      </disk>
    disk_device: |
      <disk type='file' device='disk'>
        <driver name='qemu' type='{{.DiskType}}' cache='none'/>
        <source file='{{.TargetPath}}'/>
        <target dev='{{.TargetDevice}}' bus='virtio'/>
      </disk>
    storage_volume: |
      <volume>
        <name>{{.Name}}</name>
        <allocation unit="G">0</allocation>
        <capacity unit="{{.Unit}}">{{.Size}}</capacity>
      </volume>
    manual_network_interface: |
      <interface type='network'>
        <source network='{{.NetworkName}}'/>
        <target dev='vnet0'/>
        <model type='virtio'/>
        <alias name='net0'/>
      </interface>
    vm_domain: |
      <domain type='qemu'>
        <name>{{.Name}}</name>
        <uuid>{{.UUID}}</uuid>
        <memory unit='MiB'>{{.Memory}}</memory>
        <vcpu>{{.CPU}}</vcpu>
        <os>
          <type>hvm</type>
          <boot dev='hd'/>
        </os>
        <features>
          <acpi/>
          <apic/>
          <vmport state='off'/>
        </features>
        <on_poweroff>destroy</on_poweroff>
        <on_reboot>restart</on_reboot>
        <on_crash>restart</on_crash>
        <devices>
          <emulator>/usr/bin/qemu-system-x86_64</emulator>
          <devices>
            <console type='pty'>
              <target type='serial' port='0'/>
            </console>
          </devices>
        </devices>
      </domain>
