# Rendered with Go text templates, see https://golang.org/pkg/text/template/
- type: replace
  path: /resource_pools/name=vms/cloud_properties/libvirt?
  value:
    storage_pool_name: ((libvirt_storage_pool_name))
    disk_device: |
      <disk type='file' device='disk'>
        <driver name='qemu' type='raw' cache='none'/>
        <source file='{{.TargetPath}}'/>
        <target dev='{{.TargetDevice}}'/>
      </disk>
    storage_volume: |
      <volume>
        <name>{{.Name}}</name>
        <allocation unit="G">0</allocation>
        <capacity unit="{{.Unit}}">{{.Size}}</capacity>
      </volume>
    network_interface: |
      <interface type='network'>
        <mac address='#{mac_address}'/>
        <source network='default' bridge='virbr0'/>
        <target dev='vnet0'/>
        <model type='virtio'/>
        <alias name='net0'/>
      </interface>
    vm_domain: |
      <domain type='qemu'>
        <name>#{domain_name(uuid)}</name>
        <uuid>#{uuid}</uuid>
        <memory unit='KiB'>1048576</memory>
        <vcpu placement='static'>1</vcpu>
        <resource>
          <partition>/machine</partition>
        </resource>
        <os>
          <type arch='x86_64' machine='pc-i440fx-2.8'>hvm</type>
          <boot dev='hd'/>
        </os>
        <features>
          <acpi/>
          <apic/>
          <vmport state='off'/>
        </features>
        <cpu mode='custom' match='exact'>
          <model fallback='forbid'>Skylake-Client</model>
        </cpu>
        <clock offset='utc'>
          <timer name='rtc' tickpolicy='catchup'/>
          <timer name='pit' tickpolicy='delay'/>
          <timer name='hpet' present='no'/>
        </clock>
        <on_poweroff>destroy</on_poweroff>
        <on_reboot>restart</on_reboot>
        <on_crash>restart</on_crash>
        <pm>
          <suspend-to-mem enabled='no'/>
          <suspend-to-disk enabled='no'/>
        </pm>
        <devices>
          <emulator>/usr/bin/qemu-system-x86_64</emulator>
          <disk type='file' device='disk'>
            <driver name='qemu' type='qcow2'/>
            <source file='#{volume_path}'/>
            <backingStore/>
            <target dev='vda' bus='virtio'/>
            <alias name='virtio-disk0'/>
            <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
          </disk>
          <controller type='usb' index='0' model='ich9-ehci1'>
            <alias name='usb'/>
            <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x7'/>
          </controller>
          <controller type='usb' index='0' model='ich9-uhci1'>
            <alias name='usb'/>
            <master startport='0'/>
            <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0' multifunction='on'/>
          </controller>
          <controller type='usb' index='0' model='ich9-uhci2'>
            <alias name='usb'/>
            <master startport='2'/>
            <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x1'/>
          </controller>
          <controller type='usb' index='0' model='ich9-uhci3'>
            <alias name='usb'/>
            <master startport='4'/>
            <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x2'/>
          </controller>
          <controller type='pci' index='0' model='pci-root'>
            <alias name='pci.0'/>
          </controller>
          <controller type='virtio-serial' index='0'>
            <alias name='virtio-serial0'/>
            <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
          </controller>
          #{network_interfaces_xml(networks)}
          <serial type='pty'>
            <source path='/dev/pts/3'/>
            <target port='0'/>
            <alias name='serial0'/>
          </serial>
          <console type='pty' tty='/dev/pts/3'>
            <source path='/dev/pts/3'/>
            <target type='serial' port='0'/>
            <alias name='serial0'/>
          </console>
          <channel type='spicevmc'>
            <target type='virtio' name='com.redhat.spice.0' state='disconnected'/>
            <alias name='channel0'/>
            <address type='virtio-serial' controller='0' bus='0' port='1'/>
          </channel>
          <input type='mouse' bus='ps2'>
            <alias name='input0'/>
          </input>
          <input type='keyboard' bus='ps2'>
            <alias name='input1'/>
          </input>
          <graphics type='spice' port='5900' autoport='yes' listen='127.0.0.1'>
            <listen type='address' address='127.0.0.1'/>
            <image compression='off'/>
          </graphics>
          <sound model='ich6'>
            <alias name='sound0'/>
            <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
          </sound>
          <video>
            <model type='vmvga' vram='16384' heads='1' primary='yes'/>
            <alias name='video0'/>
            <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
          </video>
          <redirdev bus='usb' type='spicevmc'>
            <alias name='redir0'/>
            <address type='usb' bus='0' port='1'/>
          </redirdev>
          <redirdev bus='usb' type='spicevmc'>
            <alias name='redir1'/>
            <address type='usb' bus='0' port='2'/>
          </redirdev>
          <memballoon model='virtio'>
            <alias name='balloon0'/>
            <address type='pci' domain='0x0000' bus='0x00' slot='0x08' function='0x0'/>
          </memballoon>
          <rng model='virtio'>
            <backend model='random'>/dev/random</backend>
            <alias name='rng0'/>
            <address type='pci' domain='0x0000' bus='0x00' slot='0x09' function='0x0'/>
          </rng>
        </devices>
        <seclabel type='none' model='none'/>
      </domain>
