# Setup for VMWare vSphere stemcell
- type: replace
  path: /resource_pools/name=vms/stemcell?
  value:
    url: https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-xenial-go_agent?v=456.12
    sha1: 2b5aa0c51fb0bead9d36b2adb7514de719476363

# This is for rendering within the VM once stood up
- type: replace
  path: /instance_groups/name=bosh/properties/libvirt_cpi?/stemcell?
  value: &stemcell_settings
    formats: [ "vsphere-ova", "vsphere-ovf" ]
    type: CDROM
    filename: env

# This is for initial standup of VM (bootstrap?)
- type: replace
  path: /cloud_provider/properties/libvirt_cpi?/stemcell?
  value: *stemcell_settings
